services:
  - type: web
    name: vue-plos-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticSite:
      buildCommand: npm install && npm run build
      publishPath: dist
